[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.96.0"

[context.production.environment]
  HUGO_ENV = "production"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
